version: '3.0'
services:
  resource-server:
    image: openmhealth/shimmer-resource-server
    depends_on:
      - mongo
    env_file:
      - resource-server.env
    links:
      - mongo:omh-mongo
    ports:
      - "8077:8083"

  mongo:
    image: mongo
    #restart: always

  postgres:
    build: ./postgresql/.
    image: beapen/drishti-postgres:latest
    #restart: always

  mysql:
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    env_file:
      - resource-server.env

  drishti-haproxy:
    build: ./haproxy/.
    image: beapen/drishti-haproxy:latest
    ports:
      - "8080:8080"
    depends_on:
      - resource-server

  drishti-cog:
    image: beapen/drishti-cog:latest
    env_file:
      - resource-server.env
    depends_on:
      - resource-server

  drishti-emr:
    image: beapen/drishti-emr:latest
    env_file:
      - resource-server.env
    depends_on:
      - mysql
