version: '3.0'
services:
  resource-server:
    image: openmhealth/shimmer-resource-server
    #restart: always
    environment:
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - mongo
    env_file:
      - resource-server.env
    links:
      - mongo:omh-mongo
    #ports:
      #- "8084:8083"

  mongo:
    image: mongo
    #restart: always

  # PostgreSQL is used to store OAuth 2.0 client credentials and access tokens.
  # TODO: prepopulation script resources/rdbms/postgresql
  postgres:
    build: ./postgresql/.
    image: beapen/drishti-postgres:latest
    #restart: always

  authorizationserver:
    image: openmhealth/omh-dsu-authorization-server:latest
    links:
      - mongo:omh-mongo
      - postgres:omh-postgres
    #ports:
      #- "8082:8082"

  dsu-resource-server:
    image: openmhealth/omh-dsu-resource-server:latest
    links:
      - mongo:omh-mongo
      - postgres:omh-postgres
    #ports:
      #- "8083:8083"

  console:
    image: openmhealth/shimmer-console
    #restart: always
    #ports:
      #- "8083:8083"
    depends_on:
      - resource-server

  #mdata-db:
    #image: postgres:latest
    #restart: always
    #expose:
      #- 5432
  drishti-haproxy:
    build: ./haproxy/.
    image: beapen/drishti-haproxy:latest
    ports:
      - "8080:8080"
      - "8077:5001"
    #networks:
      #- overlay
    depends_on:
      - resource-server

  drishti-cog:
    build: ./drishti-cog/.
    image: beapen/drishti-cog:latest
    depends_on:
      - resource-server
