version: '3.0'
services:
  resource-server:
    image: openmhealth/shimmer-resource-server
    #restart: always
    #    environment:
    #      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - mongo
    env_file:
      - resource-server.env
    links:
      - mongo:omh-mongo
    ports:
      - "8077:8083"

  mongo:
    image: mongo
    #restart: always

  # PostgreSQL is used to store OAuth 2.0 client credentials and access tokens.
  # TODO: prepopulation script resources/rdbms/postgresql
  postgres:
    build: ./postgresql/.
    image: beapen/drishti-postgres:latest
    #restart: always

  mysql:
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
 
  drishti-haproxy:
    build: ./haproxy/.
    image: beapen/drishti-haproxy:latest
    ports:
      - "8080:8080"
    #- "8081:5001"
    #networks:
    #- overlay
    depends_on:
      - resource-server

  drishti-cog:
    build: ./drishti-cog/.
    image: beapen/drishti-cog:latest
    depends_on:
      - resource-server

  drishti-emr:
    image: openmrs/openmrs-reference-application-distro
    depends_on:
      - mysql
    environment:
      DB_DATABASE: openmrs
      DB_HOST: mysql
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'true'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'true'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
    volumes:
      - ./openmrs-owa-drishti/dist:/usr/local/tomcat/.OpenMRS/owa/drishti     # used to mount persistent docker volume for owa
      #- ./openmrs-module-drishti/target:/usr/local/tomcat/.OpenMRS/modules/     # used to mount persistent docker volume for modules
